baseURL = "https://notchtc.github.io/"

theme = "hugo-bearblog"

title = "chtc"
author = "chtc"
copyright = "Â© 2021-2022 chtc"
languageCode = "en-us"

enableGitInfo = true

enableRobotsTXT = true

[params]
    title = "chtc"
