base_url = "https://notchtc.github.io"
author = "chtc"
title = "chtc"

compile_sass = true
build_search_index = false
default_language = "en"

[markdown]
bottom_footnotes = true
external_links_target_blank = true
lazy_async_image = true
render_emoji = true
smart_punctuation = false
