baseURL = "https://chtc.neocities.org/"

theme = "hugo-bearblog"

title = "chtc's decaying mental fucked-up technology state"
author = "chtc"
copyright = "Copyright Â© 2021, chtc"
languageCode = "en-us"

enableRobotsTXT = true

disableKinds = ["taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]

[permalinks]
    blog = "/blog/:slug/"
    tags = "/tag/:slug"

[params]
    description = "One site's worth of stupid af content too much (crappy description I guess)."
    title = "chtc's decaying mental state"
    hideMadeWithLine = true
    favicon = "/imgs/chtc.svg"

[markup]
    [markup.asciidocExt]
    extensions = ["asciidoctor-html5s",]
    backend = "html5s"
    preserveTOC = true
